name: AI Summarizer Automation

on:
  schedule:
    # 0 = menit ke-0, */6 = tiap 6 jam, * = tiap hari, bulan, hari dalam seminggu
    - cron: '0 */6 * * *'
  workflow_dispatch: # Supaya bisa dijalankan manual untuk tes

jobs:
  run-summarizer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install transformers supabase requests

        # --- TAMBAHKAN BARIS INI ---
      - name: Debug - Cek Isi File main.py
        run: cat bot.py
      # ---------------------------

      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python bot.py
